import { Ingredient } from "@/store/useRefrigeratorStore";
import { getIngredientImage } from "@/lib/ingredientImages";

// Comprehensive Cocktail Ingredients Database
export const initialIngredients: Ingredient[] = [
  // ========== SPIRITS ==========
  { id: "vodka", name: "Vodka", category: "spirits", image: getIngredientImage("Vodka") },
  { id: "gin", name: "Gin", category: "spirits", image: getIngredientImage("Gin") },
  { id: "white-rum", name: "White Rum", category: "spirits", image: getIngredientImage("White Rum") },
  { id: "dark-rum", name: "Dark Rum", category: "spirits", image: getIngredientImage("Dark Rum") },
  { id: "spiced-rum", name: "Spiced Rum", category: "spirits", image: getIngredientImage("Spiced Rum") },
  { id: "tequila-blanco", name: "Tequila Blanco", category: "spirits", image: getIngredientImage("Tequila Blanco") },
  { id: "tequila-reposado", name: "Tequila Reposado", category: "spirits", image: getIngredientImage("Tequila Reposado") },
  { id: "mezcal", name: "Mezcal", category: "spirits", image: getIngredientImage("Mezcal") },
  { id: "bourbon", name: "Bourbon", category: "spirits", image: getIngredientImage("Bourbon") },
  { id: "rye-whiskey", name: "Rye Whiskey", category: "spirits", image: getIngredientImage("Rye Whiskey") },
  { id: "scotch", name: "Scotch", category: "spirits", image: getIngredientImage("Scotch") },
  { id: "irish-whiskey", name: "Irish Whiskey", category: "spirits", image: getIngredientImage("Irish Whiskey") },
  { id: "brandy", name: "Brandy", category: "spirits", image: getIngredientImage("Brandy") },
  { id: "cognac", name: "Cognac", category: "spirits", image: getIngredientImage("Cognac") },
  { id: "triple-sec", name: "Triple Sec", category: "spirits", image: getIngredientImage("Triple Sec") },
  { id: "cointreau", name: "Cointreau", category: "spirits", image: getIngredientImage("Cointreau") },
  { id: "blue-curacao", name: "Blue Curaçao", category: "spirits", image: getIngredientImage("Blue Curaçao") },
  { id: "st-germain", name: "St-Germain", category: "spirits", image: getIngredientImage("St-Germain") },
  { id: "aperol", name: "Aperol", category: "spirits", image: getIngredientImage("Aperol") },
  { id: "campari", name: "Campari", category: "spirits", image: getIngredientImage("Campari") },
  { id: "amaretto", name: "Amaretto", category: "spirits", image: getIngredientImage("Amaretto") },
  { id: "kahlua", name: "Kahlúa", category: "spirits", image: getIngredientImage("Kahlúa") },
  { id: "baileys", name: "Baileys", category: "spirits", image: getIngredientImage("Baileys") },
  { id: "sweet-vermouth", name: "Sweet Vermouth", category: "spirits", image: getIngredientImage("Sweet Vermouth") },
  { id: "dry-vermouth", name: "Dry Vermouth", category: "spirits", image: getIngredientImage("Dry Vermouth") },

  // ========== MIXERS ==========
  { id: "lemon-juice", name: "Lemon Juice", category: "mixers", image: getIngredientImage("Lemon Juice") },
  { id: "lime-juice", name: "Lime Juice", category: "mixers", image: getIngredientImage("Lime Juice") },
  { id: "orange-juice", name: "Orange Juice", category: "mixers", image: getIngredientImage("Orange Juice") },
  { id: "cranberry-juice", name: "Cranberry Juice", category: "mixers", image: getIngredientImage("Cranberry Juice") },
  { id: "pineapple-juice", name: "Pineapple Juice", category: "mixers", image: getIngredientImage("Pineapple Juice") },
  { id: "grapefruit-juice", name: "Grapefruit Juice", category: "mixers", image: getIngredientImage("Grapefruit Juice") },
  { id: "tomato-juice", name: "Tomato Juice", category: "mixers", image: getIngredientImage("Tomato Juice") },
  { id: "apple-cider", name: "Apple Cider", category: "mixers", image: getIngredientImage("Apple Cider") },
  { id: "club-soda", name: "Club Soda", category: "mixers", image: getIngredientImage("Club Soda") },
  { id: "tonic-water", name: "Tonic Water", category: "mixers", image: getIngredientImage("Tonic Water") },
  { id: "ginger-beer", name: "Ginger Beer", category: "mixers", image: getIngredientImage("Ginger Beer") },
  { id: "ginger-ale", name: "Ginger Ale", category: "mixers", image: getIngredientImage("Ginger Ale") },
  { id: "cola", name: "Cola", category: "mixers", image: getIngredientImage("Cola") },
  { id: "sprite", name: "Sprite", category: "mixers", image: getIngredientImage("Sprite") },
  { id: "sparkling-wine", name: "Sparkling Wine", category: "mixers", image: getIngredientImage("Sparkling Wine") },
  { id: "heavy-cream", name: "Heavy Cream", category: "mixers", image: getIngredientImage("Heavy Cream") },
  { id: "coconut-cream", name: "Coconut Cream", category: "mixers", image: getIngredientImage("Coconut Cream") },
  { id: "egg-white", name: "Egg White", category: "mixers", image: getIngredientImage("Egg White") },

  // ========== PANTRY ==========
  { id: "simple-syrup", name: "Simple Syrup", category: "pantry", image: getIngredientImage("Simple Syrup") },
  { id: "agave-nectar", name: "Agave Nectar", category: "pantry", image: getIngredientImage("Agave Nectar") },
  { id: "honey-syrup", name: "Honey Syrup", category: "pantry", image: getIngredientImage("Honey Syrup") },
  { id: "grenadine", name: "Grenadine", category: "pantry", image: getIngredientImage("Grenadine") },
  { id: "maple-syrup", name: "Maple Syrup", category: "pantry", image: getIngredientImage("Maple Syrup") },
  { id: "angostura-bitters", name: "Angostura Bitters", category: "pantry", image: getIngredientImage("Angostura Bitters") },
  { id: "orange-bitters", name: "Orange Bitters", category: "pantry", image: getIngredientImage("Orange Bitters") },
  { id: "peychauds-bitters", name: "Peychaud's Bitters", category: "pantry", image: getIngredientImage("Peychaud's Bitters") },
  { id: "salt", name: "Salt", category: "pantry", image: getIngredientImage("Salt") },
  { id: "tajin", name: "Tajín", category: "pantry", image: getIngredientImage("Tajín") },
  { id: "tabasco", name: "Tabasco", category: "pantry", image: getIngredientImage("Tabasco") },
  { id: "worcestershire-sauce", name: "Worcestershire Sauce", category: "pantry", image: getIngredientImage("Worcestershire Sauce") },
  { id: "sugar-cubes", name: "Sugar Cubes", category: "pantry", image: getIngredientImage("Sugar Cubes") },

  // ========== GARNISHES ==========
  { id: "lemon-wedge", name: "Lemon Wedge", category: "garnishes", image: getIngredientImage("Lemon Wedge") },
  { id: "lime-wheel", name: "Lime Wheel", category: "garnishes", image: getIngredientImage("Lime Wheel") },
  { id: "orange-peel", name: "Orange Peel", category: "garnishes", image: getIngredientImage("Orange Peel") },
  { id: "maraschino-cherries", name: "Maraschino Cherries", category: "garnishes", image: getIngredientImage("Maraschino Cherries") },
  { id: "olives", name: "Olives", category: "garnishes", image: getIngredientImage("Olives") },
  { id: "cucumber-slices", name: "Cucumber Slices", category: "garnishes", image: getIngredientImage("Cucumber Slices") },
  { id: "mint-leaves", name: "Mint Leaves", category: "garnishes", image: getIngredientImage("Mint Leaves") },
  { id: "basil", name: "Basil", category: "garnishes", image: getIngredientImage("Basil") },
  { id: "rosemary", name: "Rosemary", category: "garnishes", image: getIngredientImage("Rosemary") },
  { id: "cinnamon-stick", name: "Cinnamon Stick", category: "garnishes", image: getIngredientImage("Cinnamon Stick") },
  { id: "coffee-beans", name: "Coffee Beans", category: "garnishes", image: getIngredientImage("Coffee Beans") },
];


